Repository jhthorsen/mojo-redis, pull requests merged in 2018-12, with the labels that each got.

#22 Add destructor to Connection object
  lib/Mojo/Redis/Connection.pm
  t/connection.t
Labels: bug, enhancement

#23 Add support for negative cache expire for serving stale data
  Changes
  lib/Mojo/Redis/Cache.pm
  t/cache-offline.t
  t/cache.t
Labels: enhancement

#28 Blocking connection is not fork safe
  lib/Mojo/Redis.pm
  t/connection.t
Labels: bug

#30 Use portable ERRNO constants
  t/connection-lost.t
Labels: bug

#33 Should not reconnect, since it mess up transactions
  lib/Mojo/Redis.pm
  lib/Mojo/Redis/Cache.pm
  lib/Mojo/Redis/Connection.pm
  lib/Mojo/Redis/Database.pm
  t/connection-lost.t
  t/connection.t
Labels: bug, enhancement
